spring:
  application:
    name: spellbound
  dataSource:
    url: jdbc:postgresql://localhost:5432/spell?currentSchema=public
  session:
    jdbc:
      initialize-schema: always
  mvc:
    problemdetails:
      enabled: true
  jackson:
    visibility:
      field: any
      getter: none
      setter: none
      is-getter: none